#!/bin/bash explain about it in huma understandable format?
ans:  Shebang --> It should be the first line of shell script. 
      It is the interpreter to execute the commands  and syntax inside shell script

 What is Bash?
ans: It's a command-line interpreter (shell) used in Linux and macOS systems to:
     Run commands
     Automate tasks using scripts
     Interact with the operating system.
            Bash is a program that lets you talk to your computer by typing text commands instead of clicking things.
     Think of Bash as the "translator" between you and the computer's operating system.


Can you tell me about special variables in shell scripting?
ans:  $1, $2, $3 ( these are used as aruguments for functions, when you send data to the function it will strore those like first value in $1,
      second value in $2)
      All variables passed: $@
      number of variables: $#
      script name: $0
      present working directory: $PWD
      home directory of current user: $HOME
      which user is running this script: $USER
      process id of current script: $$
      process id of last command in background: $!


How can you check previous command is success or not in shell script?
ans: By checking the exit status, if exit status is 0 it is success, otherwise it is failure
      to check exit status we should use "$?"


How do we check in shellScript that whether are we running in sudo access or not?
ans: When $(id -u) returns zero then we are running with sudo access, we can able to install commands
      if it returns 1 we are not running it with sudo access, make sure that we are running with sudo access, then run commands
      check if the user running the script is root user or not
      if root user
      	allow him
      else
      	show the error properly and exit the script
      run install command
      check installation is success
      if success, our task is done
      if not success, throw the error message






